# Generated by Django 2.0.3 on 2022-03-13 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20220313_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('idBookItem', models.AutoField(primary_key=True, serialize=False)),
                ('totalPrice', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'book_item',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('idCart', models.AutoField(primary_key=True, serialize=False)),
                ('totalPrice', models.FloatField(default=0)),
                ('createAt', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('idOrder', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Cart')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('idStatus', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'order_status',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('idPaymentType', models.AutoField(primary_key=True, serialize=False)),
                ('paymentTypeName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('idShipment', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(null=True)),
            ],
            options={
                'db_table': 'shipment',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idAccount', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('birthday', models.DateTimeField()),
                ('gender', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('idRole', models.AutoField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'userRole',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='note',
            field=models.TextField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.UserRole'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Shipment'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.OrderStatus'),
        ),
        migrations.AddField(
            model_name='bookitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Cart'),
        ),
        migrations.AddField(
            model_name='bookitem',
            name='idBook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Book'),
        ),
    ]
