# Generated by Django 2.0.3 on 2022-03-13 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20220313_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='district_id',
        ),
        migrations.AddField(
            model_name='ward',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.District'),
        ),
        migrations.AddField(
            model_name='ward',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Province'),
        ),
    ]
