# Generated by Django 4.0.2 on 2022-04-22 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_rename_user_id_userinfo_user_alter_userinfo_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 4, 23, 1, 0, 52, 222992)),
        ),
    ]
