# Generated by Django 4.0.2 on 2022-05-16 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_alter_userinfo_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('idOrderType', models.AutoField(primary_key=True, serialize=False)),
                ('orderTypeName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'order_type',
            },
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 23, 52, 23, 749748)),
        ),
    ]
