# Generated by Django 4.0.2 on 2022-05-17 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_ordertype_alter_userinfo_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiverEmail',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receiverFirstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receiverLastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 5, 17, 22, 47, 47, 428789)),
        ),
    ]
