# Generated by Django 4.0.2 on 2022-05-17 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_order_receiveremail_order_receiverfirstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 5, 17, 23, 6, 56, 536695)),
        ),
    ]
