# Generated by Django 4.0.2 on 2022-05-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_alter_userinfo_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(auto_now_add=True),
        ),
    ]
