# Generated by Django 4.0.2 on 2022-05-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_alter_userinfo_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
